<?php
// The COMMON configuration file
return [
    'SES_NAME'=>'lsn18081',
    'AUTH_NAME'=>'tK0918s',
    'avatar'=>[
        'types'=>[
            'ico'=>[
                'width'=>40,
                'height'=>40,
                'images_path'=>'img/avatars/',
            ]
        ],
        'max_file_size'=>6000000,
        'max_count'=>1,
        'field_name'=>'userFiles'
    ],
    'foto'=>[
        'types'=>[
            'ico'=>[
                'width'=>160,
                'height'=>160,
                'images_path'=>'img/fotos/ico/',
            ],
            'mini'=>[
                'width'=>375,
                'height'=>375,
                'images_path'=>'img/fotos/mini/'
            ],
            'big'=>[
                'width'=>667,
                'height'=>667,
                'images_path'=>'img/fotos/big/'
            ],
            'hi'=>[
                'width'=>1920,
                'height'=>1080,
                'images_path'=>'img/fotos/hi/'
            ]
        ],
        'max_file_size'=>20000000,
        'max_count'=>16,
        'field_name'=>'userFiles'
    ],
    'msgfoto'=>[
        'types'=>[
            'ico'=>[
                'width'=>160,
                'height'=>160,
                'images_path'=>'img/msgfotos/ico/',
            ],
            'mini'=>[
                'width'=>375,
                'height'=>375,
                'images_path'=>'img/msgfotos/mini/'
            ],
            'big'=>[
                'width'=>667,
                'height'=>667,
                'images_path'=>'img/msgfotos/big/'
            ],
            'hi'=>[
                'width'=>1920,
                'height'=>1080,
                'images_path'=>'img/msgfotos/hi/'
            ]
        ],
        'max_file_size'=>20000000,
        'max_count'=>16,
        'field_name'=>'userFiles'
    ],
    'mag_start_data'=>[
        'timeout'=>30*1000, // обновление клиента, msec
        'max_post_items_count'=>4,
        'max_post_item_text_length'=> 400,
        'colors'=>['#fff','#fee','#efe','#eef','#ffe','#fef','#eff'],
    ]
];